export type Locale = "en" | "es";

export const LOCALE_STORAGE_KEY = "darkroom-ui-locale";

export const COPY = {
  en: {
    edition: "darkroom-ui",
    nav: {
      index: "Features",
      reveal: "Theming",
      negative: "Install",
      catalog: "Components",
      primary: "Primary",
      themeToLight: "Light mode",
      themeToDark: "Dark mode",
      themeToggle: "Toggle theme",
      langAria: "Switch language",
    },
    hero: {
      version: "v0.2.0",
      kicker: "react component kit",
      titleA: "Ship",
      titleB: "clear interfaces.",
      body: "A monochrome React component library for content-heavy UIs. Paper and charcoal tokens, CSS-variable theming, tree-shakeable exports — no accent rainbow.",
      cta: "Get started",
      source: "Source code →",
      tagline: "Monochrome editorial React components",
      description:
        "A monochrome React component library for content-heavy UIs.",
    },
    features: {
      title: "What you get",
      tag: "01 — Features",
      items: [
        {
          num: "01",
          title: "Editorial components",
          desc: "Typography, cards, hero, and navigation tuned for content-heavy sites.",
          tag: "core",
        },
        {
          num: "02",
          title: "Light & dark",
          desc: "One class on html toggles the whole palette via CSS variables.",
          tag: "theming",
        },
        {
          num: "03",
          title: "Tree-shakeable",
          desc: "Import the full bundle or per-component subpaths.",
          tag: "bundle",
        },
        {
          num: "04",
          title: "Unstyled mode",
          desc: "Wire your own design tokens with slotProps.",
          tag: "headless",
        },
        {
          num: "05",
          title: "TypeScript",
          desc: "First-class types for every component and variant.",
          tag: "dx",
        },
        {
          num: "06",
          title: "Storybook",
          desc: "Interactive docs for every component in the package.",
          tag: "docs",
        },
      ],
    },
    reveal: {
      tag: "02 — Theming",
      titleA: "One token surface,",
      titleB: "light or dark.",
      body: "Toggle a class on html and the palette updates. No duplicate theme objects — just CSS variables that flip with mode.",
      light: "Light",
      dark: "Dark",
      previewLight: "html (light)",
      previewDark: "html.dark",
      miniBrand: "darkroom-ui",
      miniKicker: "media card",
      miniHeading: "Compose the page.",
      miniBody:
        "Preview how MediaCard, Heading, and Button sit together on a warm paper surface.",
      miniCta: "Docs",
      mediaAlt: "Component media preview",
      openPreview: "Open live preview",
      closePreview: "Close preview",
      modalTitle: "Live component preview",
      modalHint: "Toggle light/dark — the same tokens drive the page and this preview.",
    },
    install: {
      tag: "03 — Install",
      title: "Add it and start composing.",
      body: "Install the package, import styles once, wrap with the provider. Every component also ships as a tree-shakeable subpath export.",
      npm: "npm →",
      storybook: "Storybook →",
      shellLabel: "terminal",
      importLabel: "app entry",
      copy: "Click to copy",
      copied: "Copied",
    },
    footer: {
      line: "darkroom-ui — MIT © 2026",
    },
  },
  es: {
    edition: "darkroom-ui",
    nav: {
      index: "Features",
      reveal: "Theming",
      negative: "Install",
      catalog: "Components",
      primary: "Principal",
      themeToLight: "Modo claro",
      themeToDark: "Modo oscuro",
      themeToggle: "Alternar tema",
      langAria: "Cambiar idioma",
    },
    hero: {
      version: "v0.2.0",
      kicker: "kit de componentes react",
      titleA: "Interfaces",
      titleB: "claras, al grano.",
      body: "Una librería React monocroma para UIs con mucho contenido. Tokens papel y carbón, theming por variables CSS, exports tree-shakeable — sin arcoíris de acentos.",
      cta: "Empezar",
      source: "Código fuente →",
      tagline: "Componentes React editoriales monocromáticos",
      description:
        "Una librería React monocroma para UIs con mucho contenido.",
    },
    features: {
      title: "Qué incluye",
      tag: "01 — Features",
      items: [
        {
          num: "01",
          title: "Componentes editoriales",
          desc: "Tipografía, cards, hero y navegación pensados para sitios con mucho contenido.",
          tag: "core",
        },
        {
          num: "02",
          title: "Claro y oscuro",
          desc: "Una clase en html cambia toda la paleta vía variables CSS.",
          tag: "theming",
        },
        {
          num: "03",
          title: "Tree-shakeable",
          desc: "Importá el bundle completo o subpaths por componente.",
          tag: "bundle",
        },
        {
          num: "04",
          title: "Modo unstyled",
          desc: "Conectá tus propios design tokens con slotProps.",
          tag: "headless",
        },
        {
          num: "05",
          title: "TypeScript",
          desc: "Tipos de primera clase para cada componente y variante.",
          tag: "dx",
        },
        {
          num: "06",
          title: "Storybook",
          desc: "Docs interactivas de cada componente del paquete.",
          tag: "docs",
        },
      ],
    },
    reveal: {
      tag: "02 — Theming",
      titleA: "Una sola superficie",
      titleB: "de tokens.",
      body: "Una clase en html actualiza la paleta. Sin objetos de tema duplicados: solo variables CSS que cambian con el modo.",
      light: "Claro",
      dark: "Oscuro",
      previewLight: "html (claro)",
      previewDark: "html.dark",
      miniBrand: "darkroom-ui",
      miniKicker: "media card",
      miniHeading: "Componé la página.",
      miniBody:
        "Así se ven MediaCard, Heading y Button juntos sobre una superficie de papel cálido.",
      miniCta: "Docs",
      mediaAlt: "Vista previa del componente",
      openPreview: "Abrir preview en vivo",
      closePreview: "Cerrar preview",
      modalTitle: "Preview de componentes",
      modalHint: "Alterná claro/oscuro — los mismos tokens mueven la página y este preview.",
    },
    install: {
      tag: "03 — Install",
      title: "Instalá y empezá a componer.",
      body: "Instalá el paquete, importá los estilos una vez, envolvé con el provider. Cada componente también sale por subpath tree-shakeable.",
      npm: "npm →",
      storybook: "Storybook →",
      shellLabel: "terminal",
      importLabel: "entrada de la app",
      copy: "Clic para copiar",
      copied: "Copiado",
    },
    footer: {
      line: "darkroom-ui — MIT © 2026",
    },
  },
} as const;

export type Copy = (typeof COPY)[Locale];
